import { StyleSheet } from 'react-native';

export const emojiPageStyles = StyleSheet.create({
  openBookLeftGrid: {
    position: 'absolute',
    left: 31,
    top: 87,
    width: 85,
    height: 170,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  openBookRightGrid: {
    position: 'absolute',
    left: 170,
    top: 87,
    width: 85,
    height: 170,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
  albumChapterLabel: {
    position: 'absolute',
    left: 50,
    top: 52,
    zIndex: 1,
    color: 'rgba(96,62,34,0.74)',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  albumEmojiSlot: {
    width: 40,
    height: 50,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 4,
  },
  albumEmoji: {
    textAlign: 'center',
    fontSize: 26,
    lineHeight: 30,
    includeFontPadding: false,
  },
  albumEmojiSilhouette: {
    opacity: 0.13,
  },
  rarityDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    marginTop: 2,
  },
  stickerName: {
    fontSize: 6,
    textAlign: 'center',
    color: '#5a3e2b',
    marginTop: 1,
    width: 38,
  },
  stickerNameHidden: {
    color: '#aaa',
  },
  pageHalfEmojiGrid: {
    position: 'absolute',
    top: 19,
    width: 85,
    height: 170,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignContent: 'space-between',
  },
});
