import { StyleSheet } from 'react-native';

export const topPanelStyles = StyleSheet.create({
  timerText: {
    position: 'absolute',
    fontWeight: '900',
    color: '#fff',
    textAlign: 'center',
    textAlignVertical: 'center',
    zIndex: 10,
  },
  namePlateText: {
    position: 'absolute',
    textAlign: 'center',
    fontWeight: '900',
    letterSpacing: 1.5,
    color: '#ffd86b',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    zIndex: 20,
  },
  thoughtBubble: {
    position: 'absolute',
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#2a1608',
    backgroundColor: 'rgba(255, 248, 222, 0.96)',
    zIndex: 30,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
  },
  thoughtText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
    color: '#5a2b0c',
    textAlign: 'center',
  },
  iceRoot: {
    position: 'absolute',
    zIndex: 26,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(191,245,255,0.86)',
    backgroundColor: 'rgba(125,211,252,0.22)',
    shadowColor: '#67e8f9',
    shadowOpacity: 0.95,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    alignItems: 'center',
    justifyContent: 'center',
  },
  iceGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(186,230,253,0.24)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
  },
  iceShimmer: {
    position: 'absolute',
    top: '-14%',
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderRadius: 999,
  },
  frostCap: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    backgroundColor: 'rgba(224,251,255,0.38)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.52)',
  },
  icicle: {
    position: 'absolute',
    width: 0,
    height: 0,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'rgba(224,251,255,0.82)',
    borderStyle: 'solid',
  },
  crack: {
    position: 'absolute',
    height: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  crackThin: {
    height: 2,
    backgroundColor: 'rgba(224,251,255,0.9)',
  },
  frostShard: {
    position: 'absolute',
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.75)',
  },
  drip: {
    position: 'absolute',
    backgroundColor: 'rgba(186,230,253,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
  },
  dripSmall: {
    backgroundColor: 'rgba(224,251,255,0.82)',
  },
  freezeText: {
    marginTop: 44,
    color: '#e0fbff',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: '#0369a1',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});

