import { StyleSheet } from 'react-native';
import { CARD_SIZE } from '../../components/power-selection/powerCardStyles';
import { theme } from './luxuryTheme';

export const submenuStyles = StyleSheet.create({
  setupScroll: {
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  screenRoot: {
    flex: 1,
  },
  navBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  setupHeader: {
    alignItems: 'center',
    paddingBottom: 10,
    gap: 2,
  },
  setupEyebrow: {
    color: '#ffd700',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 3,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  setupTitle: {
    color: '#fff',
    fontSize: 32,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 6,
  },
  setupProfileName: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  powerSetupHeader: {
    alignItems: 'center',
    paddingTop: 8,
  },
  powerSetupSubtitle: {
    color: '#ffd700',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 2,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    marginTop: 4,
    marginBottom: 12,
  },
  slotRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 8,
  },
  slotWrapper: {
    width: CARD_SIZE,
    aspectRatio: 1,
    borderRadius: 12,
    shadowColor: '#7B2FBE',
    shadowOpacity: 0.6,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  slotImg: {
    width: '100%',
    height: '100%',
  },

  deckCenterArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    gap: 10,
  },
  deckWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  dotRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: -6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  dotActive: {
    width: 18,
    backgroundColor: '#FFD700',
  },
  goldenPhoenixText: {
    marginTop: -16,
    color: '#ffe8a3',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 8,
  },
  startBtn: {
    position: 'absolute',
    bottom: '18%' as any,
    alignSelf: 'center',
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  startImg: {
    width: 210,
    height: 210 * (437 / 1306),
  },
  missingText: {
    position: 'absolute',
    bottom: '14%' as any,
    alignSelf: 'center',
    color: '#ffe3b0',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    backgroundColor: 'rgba(5,3,15,0.7)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    overflow: 'hidden',
  },
  journeyContent: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  journeyTitle: {
    ...theme.title,
    marginTop: 4,
    color: '#fff7db',
    fontSize: 34,
    letterSpacing: 0,
  },
  journeyStageText: {
    marginTop: 4,
    color: '#ffe3a3',
    fontSize: 15,
    fontWeight: '900',
  },
  journeyCpuFrame: {
    marginTop: 24,
    width: 158,
    height: 158,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(255,216,107,0.72)',
    backgroundColor: 'rgba(8,4,18,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.gold,
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
  },
  journeyCpuImage: {
    width: 132,
    height: 132,
  },
  journeyButtonStack: {
    width: '100%',
    maxWidth: 310,
    gap: 12,
    marginTop: 30,
  },
  journeyDisabledButton: {
    opacity: 0.36,
  },
  journeyIntroOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    backgroundColor: 'rgba(3,2,8,0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  journeyIntroPage: {
    width: '100%',
    height: '78%',
  },
  journeyIntroButton: {
    minWidth: 240,
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: theme.gold,
    backgroundColor: 'rgba(24,9,4,0.92)',
    paddingHorizontal: 18,
    paddingVertical: 13,
    alignItems: 'center',
  },
  journeyIntroButtonText: {
    color: '#ffe3a3',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  pressed: {
    opacity: 0.78,
  },
});
