import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0d0501',
  },
  content: {
    paddingTop: 12,
    paddingBottom: 28,
    paddingHorizontal: 16,
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    minWidth: 84,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#5a3300',
    backgroundColor: '#2a1408',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#ffd86b',
    fontSize: 15,
    fontWeight: '900',
  },
  title: {
    color: '#ffd86b',
    fontSize: 28,
    fontWeight: '900',
    textShadowColor: '#3a1a00',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  headerSpacer: {
    width: 84,
  },

  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  primaryButton: {
    alignSelf: 'center',
    minWidth: 190,
    paddingHorizontal: 20,
    paddingVertical: 13,
    borderRadius: 999,
    borderWidth: 2.5,
    borderColor: '#ffd86b',
    backgroundColor: '#3a1000',
    alignItems: 'center',
    shadowColor: '#ffd86b',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
  },
  primaryButtonDisabled: {
    opacity: 0.38,
  },
  primaryButtonText: {
    color: '#ffd86b',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: '#3a1a00',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 0,
  },
  smallButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255,216,107,0.45)',
    backgroundColor: '#2a1408',
  },
  smallButtonActive: {
    backgroundColor: '#ffd86b',
    borderColor: '#5a3300',
  },
  smallButtonSecondary: {
    backgroundColor: '#2563eb',
    borderColor: '#1d4ed8',
  },
  smallButtonText: {
    color: '#ffd86b',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  smallButtonTextActive: {
    color: '#1a0a06',
  },
  deleteButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#7f1d1d',
    backgroundColor: '#2d0808',
  },
  deleteButtonText: {
    color: '#fca5a5',
    fontSize: 11,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.75,
  },

  card: {
    backgroundColor: '#160803',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#ffd86b',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 12,
    shadowColor: '#ffd86b',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  cardEyebrow: {
    color: '#ffd86b',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 2,
    textShadowColor: '#3a1a00',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 0,
  },
  activeProfileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  avatarBadge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: '#ffd86b',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a1408',
  },
  avatarEmoji: {
    fontSize: 34,
  },
  activeProfileCopy: {
    flex: 1,
    gap: 4,
  },
  activeProfileName: {
    color: '#ffd86b',
    fontSize: 24,
    fontWeight: '900',
    textShadowColor: '#3a1a00',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  activeProfileMeta: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 15,
    fontWeight: '700',
  },
  secondaryProfileWrap: {
    marginTop: 6,
    gap: 8,
  },
  secondaryEyebrow: {
    color: '#ffd86b',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  secondaryProfileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#2a1408',
    borderWidth: 1.5,
    borderColor: 'rgba(255,216,107,0.3)',
  },
  avatarBadgeSmall: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#ffd86b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileList: {
    gap: 10,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderRadius: 16,
    backgroundColor: '#2a1408',
    borderWidth: 1.5,
    borderColor: 'rgba(255,216,107,0.25)',
  },
  profileRowCopy: {
    flex: 1,
    gap: 2,
  },
  profileRowName: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },
  profileRowMeta: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    fontWeight: '700',
  },

  sectionBlock: {
    gap: 8,
  },
  input: {
    borderWidth: 2,
    borderColor: 'rgba(255,216,107,0.55)',
    backgroundColor: '#2a1408',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  sectionLabel: {
    color: '#ffd86b',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
  },
  pickerShell: {
    backgroundColor: '#2a1408',
    borderWidth: 2,
    borderColor: 'rgba(255,216,107,0.55)',
    borderRadius: 14,
    overflow: 'hidden',
  },
  picker: {
    height: 52,
    color: '#fff',
    backgroundColor: '#2a1408',
  },
  helperText: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  selectorShell: {
    minHeight: 52,
    backgroundColor: '#2a1408',
    borderWidth: 2,
    borderColor: 'rgba(255,216,107,0.55)',
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectorValue: {
    flex: 1,
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  selectorModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(5,2,2,0.88)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  selectorModalCard: {
    width: '100%',
    maxWidth: 360,
    maxHeight: 420,
    backgroundColor: '#160803',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#ffd86b',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 12,
  },
  selectorList: {
    maxHeight: 300,
  },
  selectorOption: {
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#2a1408',
    borderWidth: 1.5,
    borderColor: 'rgba(255,216,107,0.25)',
    marginBottom: 10,
  },
  selectorOptionText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyText: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 15,
  },
  errorText: {
    color: '#ff6b6b',
    fontSize: 14,
    fontWeight: '700',
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  avatarOption: {
    width: 52,
    height: 52,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: 'rgba(255,216,107,0.3)',
    backgroundColor: '#2a1408',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarOptionSelected: {
    borderColor: '#ffd86b',
    backgroundColor: '#3d1e0a',
  },
  avatarOptionText: {
    fontSize: 24,
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  colorOption: {
    minWidth: 88,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 14,
    borderWidth: 2,
    alignItems: 'center',
  },
  colorOptionSelected: {
    borderColor: '#ffd86b',
    borderWidth: 2.5,
    transform: [{ scale: 1.04 }],
  },
  colorOptionText: {
    fontSize: 13,
    fontWeight: '900',
  },
});
