import { StyleSheet } from 'react-native';

export const albumPuzzlePageStyles = StyleSheet.create({
  root: {
    flex: 1,
    overflow: 'hidden',
    backgroundColor: '#efe0bd',
  },
  leftPage: {
    borderRightWidth: 1,
    borderColor: 'rgba(68,45,25,0.3)',
  },
  rightPage: {
    borderLeftWidth: 1,
    borderColor: 'rgba(68,45,25,0.3)',
  },
  completedImage: {
    width: '100%',
    height: '100%',
  },
  lockedFrame: {
    flex: 1,
    margin: 10,
    borderWidth: 1,
    borderColor: 'rgba(112,79,43,0.44)',
    backgroundColor: '#efe2c5',
    shadowColor: '#5a3e20',
    shadowOpacity: 0.25,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  header: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    color: '#6f4b2a',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  count: {
    color: '#6f4b2a',
    fontSize: 10,
    fontWeight: '900',
  },
  hiddenPanel: {
    position: 'absolute',
    top: 58,
    left: 12,
    right: 12,
    height: 104,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(112,79,43,0.28)',
    backgroundColor: 'rgba(95,63,31,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  hiddenTitle: {
    color: '#6f4b2a',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  hiddenCopy: {
    color: 'rgba(93,61,31,0.72)',
    fontSize: 8,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 5,
  },
  pieceGrid: {
    position: 'absolute',
    top: 190,
    left: '50%',
    width: 72,
    marginLeft: -36,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    columnGap: 8,
    rowGap: 7,
  },
  pieceSlot: {
    width: 32,
    height: 32,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff7db',
    borderWidth: 1,
    borderColor: 'rgba(95,63,31,0.55)',
  },
  pieceSlotEmpty: {
    backgroundColor: 'rgba(95,63,31,0.13)',
    borderColor: 'rgba(95,63,31,0.22)',
  },
  pieceImage: {
    width: 30,
    height: 30,
  },
  emptyPieceMark: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: 'rgba(95,63,31,0.22)',
  },
  completePrompt: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 54,
    minHeight: 52,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(255,227,163,0.65)',
    backgroundColor: 'rgba(28,16,10,0.82)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 6,
  },
  completePromptTextWrap: {
    flex: 1,
  },
  completePromptTitle: {
    color: '#ffe3a3',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0,
  },
  completePromptCopy: {
    color: 'rgba(255,247,219,0.88)',
    fontSize: 7,
    fontWeight: '700',
    marginTop: 3,
  },
  completePromptClose: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,227,163,0.16)',
    marginLeft: 4,
  },
  completePromptCloseText: {
    color: '#ffe3a3',
    fontSize: 10,
    fontWeight: '900',
  },
  completeBadge: {
    position: 'absolute',
    right: 16,
    bottom: 24,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,227,163,0.86)',
  },
  completeText: {
    color: '#1c100a',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
});
