import { StyleSheet } from 'react-native';
import { theme } from '../shared/luxuryTheme';

const recapCard = {
  width: '100%' as const,
  backgroundColor: 'rgba(26,10,6,0.92)',
  borderRadius: 18,
  borderWidth: 3,
  borderColor: '#000',
  shadowColor: theme.gold,
  shadowOpacity: 0.4,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 0 },
  elevation: 12,
};

export const soloRecapStyles = StyleSheet.create({
  scroll: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 12,
  },
  shareCard: {
    width: '100%',
    gap: 12,
    padding: 12,
    borderRadius: 22,
    backgroundColor: '#120604',
  },
  pageTitle: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 4,
    color: theme.gold,
    ...theme.textShadow,
  },
  resultTitle: {
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: 2,
    color: theme.gold,
    ...theme.textShadow,
    textAlign: 'center',
    marginBottom: 4,
  },
  defeatColor: { color: '#ff4d1c' },
  victoryColor: { color: theme.gold },

  card: {
    ...recapCard,
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  profileLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarDisc: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: theme.warmBrown,
    borderWidth: 2,
    borderColor: theme.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmoji: { fontSize: 26 },
  profileName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  profileLabel: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 2,
    color: theme.gold,
    opacity: 0.75,
    marginTop: 2,
  },
  favSlot: {
    alignItems: 'center',
    gap: 4,
    minWidth: 72,
  },
  favLabel: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 2,
    color: theme.gold,
    opacity: 0.8,
  },
  favDisc: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: theme.warmBrown,
    borderWidth: 2,
    borderColor: theme.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  favEmoji: { fontSize: 30 },
  favName: {
    fontSize: 9,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    maxWidth: 68,
  },
  favPrompt: {
    fontSize: 8,
    fontWeight: '900',
    color: theme.gold,
    opacity: 0.6,
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  scoreCol: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  scoreDivider: {
    width: 2,
    height: 48,
    backgroundColor: '#3a2060',
    marginHorizontal: 8,
  },
  scoreLabel: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.5,
    color: theme.gold,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  scoreValue: {
    fontSize: 30,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  newBest: { color: theme.gold },
  newBestBadge: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1.5,
    color: theme.deepBrown,
    backgroundColor: theme.gold,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },

  highlightsCard: {
    ...recapCard,
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 10,
  },
  highlightsLabel: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 2.5,
    color: theme.gold,
    textAlign: 'center',
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  highlightsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  highlightTile: {
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  highlightDisc: {
    width: 52,
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  disc_common: { backgroundColor: '#1a1a2e', borderColor: '#ffd86b' },
  disc_rare: { backgroundColor: '#1a0a2e', borderColor: '#a855f7' },
  disc_extremelyRare: { backgroundColor: '#0a1a2e', borderColor: '#00f0ff' },
  highlightEmoji: { fontSize: 28 },
  highlightName: {
    fontSize: 9,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    maxWidth: 64,
  },
  highlightCount: {
    fontSize: 9,
    fontWeight: '900',
    color: theme.gold,
    opacity: 0.7,
  },

  rewardRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(26,10,6,0.7)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#333',
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  rewardLabel: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 2,
    color: theme.gold,
    opacity: 0.7,
  },
  rewardName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    flex: 1,
    textAlign: 'right',
  },
  rewardImage: {
    width: 32,
    height: 32,
    marginHorizontal: 8,
  },
});
